### ISSUE TITLE
guide for converting Seurat object to trendcatcher data?

### ISSUE THREAD

**Issue by wwzhang** [jaleesr/TrendCatcher#7]
I can't find any info to do this? Could you share?

**Comment by wangxinge** [comment]
Dear @wwzhang, thanks for using TrendCatcher! You can find the detailed method in our manuscript Method section. Since each Seurat object's annotation is different, we suggest you to convert it into pseudo-bulk matrix first. Each row is a gene, each column is the pseudo-bulk gene expression count (you can round up as integers). Then change the column name based on the TrendCatcher requirement, then run the analysis.
